# Generated by Django 2.2.15 on 2023-03-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialpricebar',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='partialpricebar',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='partialpricebar',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='partialpricebar',
            name='open',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricebars',
            name='close',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricebars',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricebars',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pricebars',
            name='open',
            field=models.FloatField(null=True),
        ),
    ]
