# Generated by Django 2.2.15 on 2023-03-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230304_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDBRL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_reference', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
